---
- name: Nginx exporter | Start docker Nginx exporter container
  community.docker.docker_compose_v2:
    state: present
    project_name: prometheus_nginx_exporter
    definition:
      services:
        nginx_exporter:
          image: "{{ nginx_exporter_docker_image }}"
          container_name: "{{ nginx_exporter_container_name }}"
          ports:
            - "127.0.0.1:{{ nginx_exporter_host_port }}:{{ nginx_exporter_host_port }}"
          hostname: "{{ ansible_host }}"
          restart: always
          labels: "{{ nginx_exporter_docker_labels }}"
          command: "-config-file /etc/prometheus-nginxlog-exporter.yml"
          volumes:
            - "{{ nginx_exporter_logs_dir }}:/var/log/nginx/"
            - "{{ nginx_exporter_config_dir }}/prometheus-nginxlog-exporter.yml:/etc/prometheus-nginxlog-exporter.yml"
      networks:
        default:
          external: true
          name: "{{ nginx_exporter_docker_network_name }}"
